// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/redirect/redirect.proto

package redirect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_proto_redirect_redirect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirect_redirect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_redirect_redirect_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_proto_redirect_redirect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirect_redirect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_redirect_redirect_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_proto_redirect_redirect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirect_redirect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_redirect_redirect_proto_rawDescGZIP(), []int{2}
}

func (x *InvalidateCacheRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type InvalidateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheResponse) Reset() {
	*x = InvalidateCacheResponse{}
	mi := &file_proto_redirect_redirect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheResponse) ProtoMessage() {}

func (x *InvalidateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_redirect_redirect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_redirect_redirect_proto_rawDescGZIP(), []int{3}
}

var File_proto_redirect_redirect_proto protoreflect.FileDescriptor

const file_proto_redirect_redirect_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/redirect/redirect.proto\x12\bredirect\"/\n" +
	"\x0eResolveRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"4\n" +
	"\x0fResolveResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"7\n" +
	"\x16InvalidateCacheRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"\x19\n" +
	"\x17InvalidateCacheResponse2\xa9\x01\n" +
	"\x0fRedirectService\x12>\n" +
	"\aResolve\x12\x18.redirect.ResolveRequest\x1a\x19.redirect.ResolveResponse\x12V\n" +
	"\x0fInvalidateCache\x12 .redirect.InvalidateCacheRequest\x1a!.redirect.InvalidateCacheResponseB\x17Z\x15gotiny/proto/redirectb\x06proto3"

var (
	file_proto_redirect_redirect_proto_rawDescOnce sync.Once
	file_proto_redirect_redirect_proto_rawDescData []byte
)

func file_proto_redirect_redirect_proto_rawDescGZIP() []byte {
	file_proto_redirect_redirect_proto_rawDescOnce.Do(func() {
		file_proto_redirect_redirect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_redirect_redirect_proto_rawDesc), len(file_proto_redirect_redirect_proto_rawDesc)))
	})
	return file_proto_redirect_redirect_proto_rawDescData
}

var file_proto_redirect_redirect_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_redirect_redirect_proto_goTypes = []any{
	(*ResolveRequest)(nil),          // 0: redirect.ResolveRequest
	(*ResolveResponse)(nil),         // 1: redirect.ResolveResponse
	(*InvalidateCacheRequest)(nil),  // 2: redirect.InvalidateCacheRequest
	(*InvalidateCacheResponse)(nil), // 3: redirect.InvalidateCacheResponse
}
var file_proto_redirect_redirect_proto_depIdxs = []int32{
	0, // 0: redirect.RedirectService.Resolve:input_type -> redirect.ResolveRequest
	2, // 1: redirect.RedirectService.InvalidateCache:input_type -> redirect.InvalidateCacheRequest
	1, // 2: redirect.RedirectService.Resolve:output_type -> redirect.ResolveResponse
	3, // 3: redirect.RedirectService.InvalidateCache:output_type -> redirect.InvalidateCacheResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_redirect_redirect_proto_init() }
func file_proto_redirect_redirect_proto_init() {
	if File_proto_redirect_redirect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_redirect_redirect_proto_rawDesc), len(file_proto_redirect_redirect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_redirect_redirect_proto_goTypes,
		DependencyIndexes: file_proto_redirect_redirect_proto_depIdxs,
		MessageInfos:      file_proto_redirect_redirect_proto_msgTypes,
	}.Build()
	File_proto_redirect_redirect_proto = out.File
	file_proto_redirect_redirect_proto_goTypes = nil
	file_proto_redirect_redirect_proto_depIdxs = nil
}
