// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/keygen/keygen.proto

package keygen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_proto_keygen_keygen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keygen_keygen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_keygen_keygen_proto_rawDescGZIP(), []int{0}
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_proto_keygen_keygen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keygen_keygen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_keygen_keygen_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_keygen_keygen_proto protoreflect.FileDescriptor

const file_proto_keygen_keygen_proto_rawDesc = "" +
	"\n" +
	"\x19proto/keygen/keygen.proto\x12\x06keygen\"\x0f\n" +
	"\rGetKeyRequest\"\"\n" +
	"\x0eGetKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2H\n" +
	"\rKeyGenService\x127\n" +
	"\x06GetKey\x12\x15.keygen.GetKeyRequest\x1a\x16.keygen.GetKeyResponseB\x15Z\x13gotiny/proto/keygenb\x06proto3"

var (
	file_proto_keygen_keygen_proto_rawDescOnce sync.Once
	file_proto_keygen_keygen_proto_rawDescData []byte
)

func file_proto_keygen_keygen_proto_rawDescGZIP() []byte {
	file_proto_keygen_keygen_proto_rawDescOnce.Do(func() {
		file_proto_keygen_keygen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keygen_keygen_proto_rawDesc), len(file_proto_keygen_keygen_proto_rawDesc)))
	})
	return file_proto_keygen_keygen_proto_rawDescData
}

var file_proto_keygen_keygen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_keygen_keygen_proto_goTypes = []any{
	(*GetKeyRequest)(nil),  // 0: keygen.GetKeyRequest
	(*GetKeyResponse)(nil), // 1: keygen.GetKeyResponse
}
var file_proto_keygen_keygen_proto_depIdxs = []int32{
	0, // 0: keygen.KeyGenService.GetKey:input_type -> keygen.GetKeyRequest
	1, // 1: keygen.KeyGenService.GetKey:output_type -> keygen.GetKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_keygen_keygen_proto_init() }
func file_proto_keygen_keygen_proto_init() {
	if File_proto_keygen_keygen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keygen_keygen_proto_rawDesc), len(file_proto_keygen_keygen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keygen_keygen_proto_goTypes,
		DependencyIndexes: file_proto_keygen_keygen_proto_depIdxs,
		MessageInfos:      file_proto_keygen_keygen_proto_msgTypes,
	}.Build()
	File_proto_keygen_keygen_proto = out.File
	file_proto_keygen_keygen_proto_goTypes = nil
	file_proto_keygen_keygen_proto_depIdxs = nil
}
