// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/keygen/keygen.proto

package keygen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyGenService_GetKey_FullMethodName = "/keygen.KeyGenService/GetKey"
)

// KeyGenServiceClient is the client API for KeyGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyGenServiceClient interface {
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
}

type keyGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyGenServiceClient(cc grpc.ClientConnInterface) KeyGenServiceClient {
	return &keyGenServiceClient{cc}
}

func (c *keyGenServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KeyGenService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyGenServiceServer is the server API for KeyGenService service.
// All implementations must embed UnimplementedKeyGenServiceServer
// for forward compatibility.
type KeyGenServiceServer interface {
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	mustEmbedUnimplementedKeyGenServiceServer()
}

// UnimplementedKeyGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyGenServiceServer struct{}

func (UnimplementedKeyGenServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeyGenServiceServer) mustEmbedUnimplementedKeyGenServiceServer() {}
func (UnimplementedKeyGenServiceServer) testEmbeddedByValue()                       {}

// UnsafeKeyGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyGenServiceServer will
// result in compilation errors.
type UnsafeKeyGenServiceServer interface {
	mustEmbedUnimplementedKeyGenServiceServer()
}

func RegisterKeyGenServiceServer(s grpc.ServiceRegistrar, srv KeyGenServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyGenService_ServiceDesc, srv)
}

func _KeyGenService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyGenService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyGenService_ServiceDesc is the grpc.ServiceDesc for KeyGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keygen.KeyGenService",
	HandlerType: (*KeyGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _KeyGenService_GetKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keygen/keygen.proto",
}
